exports.config = {
  fullUrl: 'http://hub.mobven.com:6008/wd/hub',
  host: 'hub.mobven.com',
  port: 6008,
  // eslint-disable-next-line radix
  wport: 2000,
  capabilities: {
    autoGrantPermissions: true,
    browserName: '',
    xcodeOrgId: 'CH3LB52K62', // 'RE9892F24F',
    xcodeSigningId: 'iPhone Developer',
    keychainPath: '/Users/mobven/Library/Keychains/appium2.keychain',
    keychainPassword: 'appium',
    wdaLocalPort: 2000,
    remoteDebugProxy: 2000,
    systemPort: 2000,
    ignoreUnimportantViews: false,
    unicodeKeyboard: true,
    resetKeyboard: true,
    wdaLaunchTimeout: 100000,
    wdaConnectionTimeout: 1000000,
    platformName: 'ios',
    platformVersion: '4.1',
    deviceName: 'deviceId',
    automationName: 'automationName',
    udid: 'udid',
    app: 'app',
    clearSystemFiles: true,
    usePrebuiltWDA: true,
    useNewWDA: false,
    disableWindowAnimation: true,
    fullReset: false,
    noReset: false,
    newCommandTimeout: 340000,
  },
};
